version: '2'

services:
  web:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8115:4000"
    volumes:
      - .:/code/build
    networks:
      - swc_website_default

networks:
  swc_website_default:
    external:
      name: swc_website_default
